# Generated by Django 5.2.4 on 2025-07-10 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCiudad', models.CharField(max_length=100, verbose_name='Nombre de la ciudad')),
                ('codigoPostal', models.CharField(max_length=10, verbose_name='Código postal')),
                ('provincia', models.CharField(max_length=100, verbose_name='Provincia')),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
            },
        ),
        migrations.AlterField(
            model_name='equipo',
            name='ciudad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='torneo.ciudad', verbose_name='Ciudad'),
        ),
    ]
